### ISSUE TITLE
highlight entire row on hover / select

### ISSUE THREAD

**Issue by adamjimenez** [deitch/jstree-grid#155]
highlight all the cells in a row when hovering or selecting.

**Comment by deitch** [comment]
Didn't we do this already? See https://github.com/deitch/jstree-grid/blob/master/jstreegrid.js#L296 and for the next 20 lines?

**Comment by adamjimenez** [comment]
Could be a regression. I remember a couple of minor issues with this. It was a little laggy and didn't highlight the left side of the expanded node. A new approach perhaps..

**Comment by deitch** [comment]
Could be. I remember the issue when it was raised. It all focuses on `findDataNode()` to determine which node to get.

**Comment by deitch** [comment]
OK, the jstree-grid code is working correctly. It is adding `.jstree-hovered` to the correct nodes. But for some reason those nodes are *not* inheriting the styles for it.

**Comment by deitch** [comment]
Oh right, here is why. In an earlier version of jstree, it just applied the styles to `.jstree-hovered`. But now:

````css
.jstree-default .jstree-hovered {
    background: #e7f4f9 none repeat scroll 0 0;
    border-radius: 2px;
    box-shadow: 0 0 1px #ccc inset;
}
````

It has to be a descendant of `.jstree-default`. Ugh. I didn't want to reimplement the styles directly; better for it to inherit.
